<a href="https://colab.research.google.com/github/SoyabulIslamLincoln/Learn_pytorch/blob/main/Pytorch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
x= torch.ones(2,2, requires_grad= True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y= x+5
print(y)



tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [5]:
print(y.grad_fn)

In [13]:
z= x*y*3
out=z.mean()
print(z, out)
print(z.grad_fn)

tensor([[18., 18.],
        [18., 18.]], grad_fn=<MulBackward0>) tensor(18., grad_fn=<MeanBackward0>)


In [9]:
a= torch.randn(2,4)
a=((a*4)/ (a-2))
print(a.requires_grad)
print('\n')
print('...............')
a.requires_grad_(True)
print(a.requires_grad)


b= (a*a*a).sum()
print(b.grad_fn)

False


...............
True


In [15]:
out.backward()

In [18]:
print(x.grad)

tensor([[5.2500, 5.2500],
        [5.2500, 5.2500]])


# *Vector_jacobian Product*

In [20]:
x=torch.randn((3,3), requires_grad= True)

y= x*2

while y.data.norm() <1000:
  y= y*2
print(y)

tensor([[ 630.2293,  625.6577,  554.0425],
        [ 909.0107,  461.0019,  378.0074],
        [-173.1994,   80.9338,  -84.3679]], grad_fn=<MulBackward0>)


In [21]:
v= torch.tensor([[1.01, 0.05, 2.3], [2.5, 4.7, 2.2], [1.3, 4.5, 7.8]], dtype= torch.float)
y.backward(v)

print(x.grad)

tensor([[ 517.1200,   25.6000, 1177.6000],
        [1280.0000, 2406.3999, 1126.4000],
        [ 665.6000, 2304.0000, 3993.6001]])


In [24]:
print(x.requires_grad)
print('\n')
print((x**5).requires_grad)
print('\n')

with torch.no_grad():
  print((x**3).requires_grad)

True


True


False


In [25]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
