<a href="https://colab.research.google.com/github/SoyabulIslamLincoln/Learn_pytorch/blob/main/Pytorch_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import print_function
import torch
import numpy as np

a= np.ones(5)
b= torch.from_numpy(a)

np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [4]:
x= torch.randn(1)
if torch.cuda.is_available():
  device = torch.device("cuda")
  
  y = torch.ones_like(x, device= device)
  x = x.to(device)
  z = x+y
  print(z)
  print(z.to("cpu", torch.double))

tensor([0.5026], device='cuda:0')
tensor([0.5026], dtype=torch.float64)


In [6]:
x= torch.empty(5,3)
print(x)

tensor([[-2.4142e-01,  0.0000e+00, -9.6483e-17],
        [ 1.6057e-39,  7.1746e-42,  1.3000e-39],
        [-9.7350e-17,  1.6064e-39,  7.1746e-42],
        [ 1.3000e-39, -9.8218e-17,  1.6071e-39],
        [ 7.1746e-42,  1.3000e-39, -9.9085e-17]])


In [7]:
x = torch.rand(5,3)
print(x)

tensor([[0.2042, 0.7571, 0.3267],
        [0.9236, 0.0977, 0.2108],
        [0.5307, 0.1357, 0.2645],
        [0.2077, 0.1168, 0.4475],
        [0.8634, 0.5650, 0.7590]])


In [10]:
x = torch.ones(5,3, dtype= torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [11]:
x.type()

'torch.LongTensor'

In [12]:
x = x.new_ones(5, 3, dtype= torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [14]:
x= torch.randn_like(x, dtype= torch.float)
print(x)

tensor([[-0.4423, -0.4718, -1.3410],
        [ 0.2022,  0.8314,  0.3232],
        [ 1.2811, -0.9014, -0.7767],
        [-2.3620, -0.2148,  0.0113],
        [ 0.7023,  0.5752,  1.2510]])


# **Diffrent type of sum techniques**

In [16]:
y= torch.rand(5, 3)
print(x+y)
#using add
print(torch.add(x,y))

result= torch.empty(5,3)
torch.add(x, y, out= result)
print(result)

tensor([[-0.3104, -0.2026, -0.7738],
        [ 0.2734,  1.1353,  0.8651],
        [ 2.0926, -0.1091, -0.6196],
        [-1.6671,  0.4833,  0.4107],
        [ 1.3378,  1.1125,  1.4908]])
tensor([[-0.3104, -0.2026, -0.7738],
        [ 0.2734,  1.1353,  0.8651],
        [ 2.0926, -0.1091, -0.6196],
        [-1.6671,  0.4833,  0.4107],
        [ 1.3378,  1.1125,  1.4908]])
tensor([[-0.3104, -0.2026, -0.7738],
        [ 0.2734,  1.1353,  0.8651],
        [ 2.0926, -0.1091, -0.6196],
        [-1.6671,  0.4833,  0.4107],
        [ 1.3378,  1.1125,  1.4908]])


In [17]:
y.add_(x)
print(y)

tensor([[-0.3104, -0.2026, -0.7738],
        [ 0.2734,  1.1353,  0.8651],
        [ 2.0926, -0.1091, -0.6196],
        [-1.6671,  0.4833,  0.4107],
        [ 1.3378,  1.1125,  1.4908]])


# **Numpy to torch and torch to numpy**

In [19]:
a = np.ones((5,3))
b= torch.from_numpy(a)
print(b)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
