<a href="https://colab.research.google.com/github/SoyabulIslamLincoln/Learn_pytorch/blob/main/Torch_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.conv1= nn.Conv2d(1,6,3)
    self.conv2 = nn.Conv2d(6, 16, 3)


    self.fc1 = nn.Linear(16*6*6, 120)
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84,10)


  def forward(self, x):
    x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
    x = F.max_pool2d(F.relu(self.conv2(x)),2)
    x= x.view(-1, self.num_flat_features(x))
    x= F.relu(self.fc1(x))
    x= F.relu(self.fc2(x))
    return x


  def num_flat_features(self, x):
    size= x.size()[1:]
    num_features= 1
    for s in size:
      num_features *=s
    return num_features

net= Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [ ]:
params= list(net.parameters())
print(params)

print(len(params))
print(params[1].size())


[Parameter containing:
tensor([[[[ 0.0501, -0.0636, -0.2260],
          [ 0.0520,  0.0505, -0.0345],
          [ 0.2259,  0.0689, -0.2294]]],


        [[[ 0.1027,  0.2927,  0.0744],
          [-0.1132, -0.2103,  0.0432],
          [-0.0199,  0.0699, -0.0075]]],


        [[[-0.1936, -0.0456,  0.3234],
          [-0.0081,  0.1370,  0.1332],
          [ 0.1981, -0.0071, -0.0401]]],


        [[[ 0.2201,  0.0573, -0.1353],
          [-0.1130,  0.0622, -0.1330],
          [-0.1215, -0.0628, -0.2610]]],


        [[[-0.1385, -0.1539,  0.1306],
          [-0.1281,  0.2892, -0.2324],
          [ 0.2478,  0.2870,  0.1630]]],


        [[[ 0.2029, -0.0755, -0.0965],
          [ 0.0342,  0.0988, -0.1360],
          [-0.2983, -0.1117,  0.1782]]]], requires_grad=True), Parameter containing:
tensor([-0.1703, -0.2546, -0.3190,  0.0061, -0.0392, -0.0794],
       requires_grad=True), Parameter containing:
tensor([[[[-0.0118,  0.1242,  0.1297],
          [ 0.0646,  0.0305,  0.0077],
          [ 0.0170

In [ ]:
input= torch.randn(1,1,32,32)
out= net(input)
out


tensor([[0.0423, 0.0000, 0.0320, 0.0000, 0.0000, 0.0000, 0.1232, 0.0000, 0.0702,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0623, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.1313, 0.0000, 0.0000, 0.0000, 0.0841, 0.0488, 0.0000,
         0.0569, 0.0873, 0.0736, 0.0999, 0.0000, 0.0683, 0.1107, 0.1453, 0.0000,
         0.0000, 0.0509, 0.0251, 0.0761, 0.0000, 0.0801, 0.0000, 0.0000, 0.0000,
         0.0112, 0.0000, 0.0493, 0.0672, 0.1544, 0.0000, 0.1798, 0.1486, 0.0000,
         0.0575, 0.0275, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1182, 0.0000,
         0.0000, 0.2052, 0.0000, 0.0000, 0.0472, 0.0000, 0.1264, 0.0619, 0.1310,
         0.0353, 0.0000, 0.0971, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0108,
         0.0000, 0.0000, 0.0000]], grad_fn=<ReluBackward0>)